server:
  port: 8088
  sleuth:
    sampler:
      percentage: 0.1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka